- README.md
- composer.lock
- phpstan.neon
- src/Framework/resource/layout/main.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/ContactForm.php
- src/UseCase/Contact/view/index.php
- src/UseCase/Controller.php
- src/UseCase/Site/view/error.php
- tests/Unit/Contact/ContactFormTest.php
> `PHPStan` level 5.

- src/Framework/resource/layout/main.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/view/index.php
- src/UseCase/Controller.php
- tests/Functional/Contact/IndexCest.php
> Fix layout.

- config/test.php
- config/web.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/ContactForm.php
- src/UseCase/Controller.php
> Dependency injection.

- src/Framework/resource/layout/component/alert.php
- src/Framework/resource/layout/main.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/view/index.php
> Add alert widget.

- .gitignore
- composer.json
- composer.lock
- config/config-plugin.php
- config/params.php
- config/web.php
- src/Framework/resource/layout/component/menu.php
- src/UseCase/Contact/ContactForm.php
- web/index-test.php
- web/index.php
> Use `yiisoft/config`.

- config/config-plugin.php
- config/console.php
- config/test.php
- config/web.php
- web/index-test.php
- web/index.php
- yii
> Add `console` to `yiisoft/config`.

- src/Framework/Asset/AppAsset.php
- src/Framework/resource/layout/component/alert.php
- src/Framework/resource/layout/component/menu.php
- src/UseCase/Contact/view/index.php
> More clean code.

- src/UseCase/Contact/ContactController.php
- src/UseCase/Controller.php
> Fix minor correction.

- config/config-plugin.php
- config/test.php
- config/web/bootstrap.php
- src/Events.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/ContactEvent.php
> Add `bootstrap` config with `events`.

- config/web/bootstrap.php
- src/Framework/EventHandler/ContactEventHandler.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/ContactEvent.php
> Better naming.

- src/Framework/resource/css/site.css
- src/Framework/resource/layout/component/menu.php
- src/Framework/resource/layout/footer.php
- src/Framework/resource/layout/main.php
- src/UseCase/About/view/index.php
- src/UseCase/Contact/view/index.php
> Fix css corrections.

- public/index.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/view/index.php
- src/UseCase/Controller.php
> Add `Ajax` in forms.

- README.md
- composer.lock
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/view/index.php
- src/UseCase/Controller.php
- tests/Acceptance.suite.yml
> Fix minor corrections.

- config/console/app.php
- config/params-console.php
- config/params-web.php
- config/tests.php
- config/web/app.php
- config/web/components.php
- config/web/container.php
- src/Framework/resource/layout/component/menu.php
- src/Framework/resource/layout/main.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/ContactEvent.php
- src/UseCase/Contact/view/index.php
- src/UseCase/Site/SiteController.php
- src/UseCase/Site/view/404.php
- src/UseCase/Site/view/index.php
- tests/Functional/Contact/IndexCest.php
- tests/Unit/Contact/ContactFormTest.php
> Improve config.

- tests/Acceptance/AboutCest.php
- tests/Acceptance/ContactCest.php
- tests/Acceptance/SiteCest.php
- tests/Functional/ContactCest.php
- tests/Unit/ContactFormTest.php
> Improve tests.

- config/params-console.php
- src/UseCase/Contact/ContactForm.php
- src/UseCase/Hello/HelloController.php
- src/UseCase/Site/SiteController.php
- tests/Unit/HelloControllerTest.php
> Add example console command.

- README.md
- config/config-plugin.php
- config/params-web.php
- public/index.php
> Fix hard code in config.

- README.md
- composer.lock
- tests/Acceptance.suite.yml
> Use yii-serve.

- composer.json
- composer.lock
- src/Framework/resource/layout/component/toggle_dark.php
> Fix toggle theme.

- config/build.php
- config/params-web.php
- tests/Acceptance/SiteCest.php
> Update language config.

- composer.json
- composer.lock
- src/Framework/resource/layout/component/alert.php
- src/Framework/resource/layout/component/toggle_language.php
- src/Framework/resource/layout/component/toggle_theme.php
- src/Framework/resource/layout/footer.php
- src/Framework/resource/layout/head.php
- src/Framework/resource/layout/main.php
- src/UseCase/About/view/index.php
> Use widgets agnostic.

- public/index.php
> Fix `index.php`.

- public/index.php
> Use injection dependency for `Application::class`.

- composer.json
- composer.lock
- config/config-plugin.php
- src/Framework/Asset/AppAsset.php
- src/Framework/Asset/ToggleThemeAsset.php
| Fixed issues |  https://github.com/yiisoft/config/issues/151
> Update version `yiisoft/config`.

- src/Framework/EventHandler/ContactEventHandler.php
- src/UseCase/Contact/ContactController.php
- src/UseCase/Contact/Index/IndexAction.php
- tests/Unit/ContactControllerCest.php
> Refactor contact form handling.

- composer.lock
- config/params-console.php
- config/params-web.php
- config/web/app.php
- config/web/components.php
- yii
> Update web configuration.

- yii
> Fix error typo in Yii console script.

- composer.json
> Update yii2-extensions/debug version.

- composer.lock
- src/Framework/resource/layout/component/toggle_language.php
- src/Framework/resource/layout/component/toggle_theme.php
- src/UseCase/Contact/view/index.php
> Update Captcha template and toggle button in language and theme components.

- src/Framework/resource/layout/footer.php
- src/Framework/resource/layout/head.php
- src/Framework/resource/layout/main.php
- src/UseCase/Contact/view/index.php
> Update last change `phpforge/html`.

- src/Framework/resource/layout/footer.php
- src/Framework/resource/layout/head.php
- src/Framework/resource/layout/main.php
- src/UseCase/Contact/Index/IndexAction.php
- src/UseCase/Contact/view/index.php
- src/UseCase/Site/view/404.php
- src/UseCase/Site/view/about.php
- src/UseCase/Site/view/index.php
> Update `PHPForge\Html` namespaces.

- src/Framework/resource/layout/component/toggle_language.php
- src/Framework/resource/layout/component/toggle_theme.php
- src/UseCase/Site/view/404.php
> Refactor toggle buttons in language and theme components.

- composer.json
- src/Framework/resource/layout/component/alert.php
- src/Framework/resource/layout/component/menu.php
- src/Framework/resource/layout/component/toggle_language.php
- src/Framework/resource/layout/footer.php
> Use `ui-awesome/html-component-bootstrap5` package.

- src/Framework/resource/layout/component/alert.php
- src/Framework/resource/layout/component/menu.php
- src/Framework/resource/layout/component/toggle_language.php
- src/Framework/resource/layout/footer.php
> Update last changes `ui/awesome-html-component-bootstrap5`.

- docs/configuration.md
> docs: Improve clarity in configuration reference by refining section headings and descriptions.

- LICENSE.md
- README.md
> fix: Update license badge in `README.md` for improved visibility and consistency.

- composer.json
> fix: Add `minimum-stability` setting to `composer.json` for dependency management.

- CHANGELOG.md
- composer.json
- composer.lock
- config/common/components.php
> Sync to main branch.

- CHANGELOG.md
- README.md
> fix(docs): Update links and headings in `README.md` for clarity and consistency.

- CHANGELOG.md
- README.md
> Sync to main branch. 

- CHANGELOG.md
- README.md
> fix(docs): Update badge links in `README.md` to include branch query for `nginx`.

- CHANGELOG.md
- README.md
> fix(docs): Add GHCR badge for Apache image in `README.md`.

- README.md
> fix(docs): Update package badge in `README.md` to reflect latest stable version.
